
services:
  backend:
    build: ./back
    container_name: fastapi_back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    restart: always

  frontend:
    build: ./front
    container_name: streamlit_front
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always
